CREATE TABLE IF NOT EXISTS clientes (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    nome VARCHAR (100) NOT NULL,
    sobrenome VARCHAR (100) NOT NULL,
    nascimento DATE NOT NULL,
    id INT UNSIGNED NOT NULL,
    PRIMARY KEY (id),
    
);