CREATE TABLE IF NOT EXISTS  endereco ( 
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    logradouro VARCHAR (100) NOT NULL,
    bairro VARCHAR (100) NOT NULL,
    cidade VARCHAR (100) NOT NULL,
    estado VARCHAR (2) NOT NULL,
	cep VARCHAR (9) NOT NULL,
	PRIMARY KEY (id),
);
